<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>example</AssemblyName>
    <MonoGamePlatform>DesktopVK</MonoGamePlatform>
  </PropertyGroup>
  <ItemGroup>
    <!-- <ProjectReference
      Include="..\..\MonoGame\src\NuGetPackages\MonoGame.Framework\MonoGame.Framework.csproj" />
    <ProjectReference
      Include="..\..\MonoGame\src\NuGetPackages\MonoGame.Runtime.Linux.Vulkan\MonoGame.Runtime.Linux.Vulkan.csproj"
    />
    <ProjectReference
      Include="..\..\MonoGame\src\NuGetPackages\MonoGame.Runtime.Mac.Vulkan\MonoGame.Runtime.Mac.Vulkan.csproj"
    /> -->
    <PackageReference Include="MonoGame.Framework.Content.Pipeline" Version="3.8.5-preview.*" />
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5-local.*" />
    <PackageReference Include="MonoGame.Runtime.Windows.Vulkan" Version="3.8.5-local.*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\example.Core\example.Core.csproj" />
  </ItemGroup>
  <Import Project="..\example.Content\BuildContent.targets" />
</Project>